### ISSUE TITLE
AwsCredentials import raising PydanticUserError

### ISSUE THREAD

**Issue by austinweisgrau** [PrefectHQ/prefect-aws#325] opened 2023-10-16 23:54 UTC
Running `from prefect_aws import AwsCredentials` is raising this error:

```
>>> from prefect_aws import AwsCredentials
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/prefect_aws/__init__.py", line 2, in <module>
    from .credentials import AwsCredentials, MinIOCredentials
  File "/usr/local/lib/python3.10/site-packages/prefect_aws/credentials.py", line 12, in <module>
    from prefect_aws.client_parameters import AwsClientParameters
  File "/usr/local/lib/python3.10/site-packages/prefect_aws/client_parameters.py", line 10, in <module>
    class AwsClientParameters(BaseModel):
  File "/usr/local/lib/python3.10/site-packages/prefect_aws/client_parameters.py", line 77, in AwsClien
tParameters
    def deprecated_verify_cert_path(cls, values: Dict[str, Any]) -> Dict[str, Any]:
  File "/usr/local/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 222, in 
root_validator
    return root_validator()(*__args)  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/pydantic/deprecated/class_validators.py", line 228, in 
root_validator
    raise PydanticUserError(
pydantic.errors.PydanticUserError: If you use `@root_validator` with pre=False (the default) you MUST s
pecify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@
model_validator`.

For further information visit https://errors.pydantic.dev/2.4/u/root-validator-pre-skip
```
prefect version: 2.13.4
prefect-aws version: 0.2.5

Note that upgrading prefect to 2.13.7 and prefect-aws to 0.4.1 fixes this issue. But this issue represents some kind of breaking change or incompatibility even without major version changes.

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-aws/#contributing) a pull request to resolve this!

**Comment by austinweisgrau** [comment] 2023-10-17 00:20
I believe this has to do with an update to the prefect version. This error does not occur with prefect 2.12.x

**Comment by urimandujano** [comment] 2023-10-17 14:57
Hey @austinweisgrau -- can you double check the prefect version you're running? The reason I ask is because we added experimental support for pydantic v2 in [prefect v2.13.5](https://github.com/PrefectHQ/prefect/releases/tag/2.13.5) and in [prefect-aws v0.4.0](https://github.com/PrefectHQ/prefect-aws/releases/tag/v0.4.0).

Would you mind sharing what your `pip freeze` output looks like? And just to be sure would you mind hopping into a REPL where you saw the error and sharing the output of `prefect.__version__`?

**Comment by austinweisgrau** [comment] 2023-10-19 20:37
You're right - from the traceback above it looks like pydantic 2.x was installed and that was the source of the problem.

This issue was arising because I am using the `prefecthq/prefect:2-python3.10` docker image, which as of recently is including pydantic 2.x and is no longer compatible with `prefect-aws < 0.4.0` unless the pydantic version is constrained.

**Comment by austinweisgrau** [comment] 2023-10-19 20:51
Really honing in on what goes wrong here, installing `prefect-aws < 0.4.0` does not constrain the pydantic version, so it allows/installs an incompatible pydantic version by default.

In a new virtual environment, running `pip install "prefect-aws==0.2.5"` will reproduce the error in this issue.

**Comment by urimandujano** [comment] 2023-11-01 22:56
Hey @austinweisgrau, it does seem like the issue is that earlier versions of our collections do not constrain the pydantic version. Part of the issue is that `prefect` and `prefect-aws` don't have pins on each other which makes it possible to install a version of `prefect` that supports pydantic v2 and a version of `prefect-aws` that does not, which is what's going on above.

What we've done as a long-term fix is update all of our collections' pins to rely on the most recent `prefect` version that supports pydantic v2. This will let pip prevent situations like the above from happening in the future -- new versions of the collections that support pydantic v2 will require a version of `prefect` that also supports pydantic v2. 

For this issue, the solution is going to be to install `prefect-aws>=0.4.0`  && `prefect>=2.13.5` in environments where `pydantic>=2.0` are installed. If there is an issue upgrading to `prefect-aws>=0.4.0`, your best bet is going to be to use a project pin on `pydantic==1.10.13`.

**Comment by urimandujano** [comment] 2023-11-14 22:18
I'm going to close this issue now because:

1. There's no way to retroactively update our pins for earlier releases
2. We've released updates across all of our collections to ensure that they're co-installed with `prefect>=2.13.5`(which is what properly constrains our pydantic dependency)

The best move going forward is going to be to use the latest release of the collection (in this case, `prefect-aws`). If unable to upgrade to the latest collection release, please pin to `pydantic==1.10.13`. Feel free to reopen this if there are issues even after trying out the options above. Thanks!

**Closed by urimandujano** 2023-11-14 22:18 UTC
